name: frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: 1.4.0
  dio: ^5.3.3
  http_parser: ^4.0.2
  google_fonts: ^6.1.0
  #audio
  audioplayers: ^5.2.1
  #router
  cached_network_image: ^3.3.1
  go_router: ^14.2.7
  #picker
  image_picker: ^1.1.2
  universal_html: ^2.0.8
  web: ^1.1.0

  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  file_picker: ^10.1.9
  path: ^1.8.3
  permission_handler: ^11.3.0
  file_selector: 1.0.3
  flutter_riverpod: ^2.5.1
  just_audio: ^0.9.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
